version: '3'

networks:
  psr-http-interfaces:

services:
  php:
    image: php:${PHP_VERSION}-fpm-alpine
    container_name: php
    volumes:
      - ..:/var/www/html
    ports:
      - "9000:9000"
    working_dir: /var/www/html
    networks:
      - psr-http-interfaces
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ..:/var/www/html
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${HTTP_PORT}:80"
    depends_on:
      - php
    working_dir: /var/www/html
    networks:
      - psr-http-interfaces
